---
development:
  dialect: postgres
  database: goatsnap_development
  user: goatsnap
  password: 20goatsnapto10
  host: 127.0.0.1
  pool: 5

test:
  dialect: postgres
  database: goatsnap_test
  user: goatsnap
  password: 20goatsnapto10
  host: 127.0.0.1

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/goatsnap_production?sslmode=disable"}}
