{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "goatsnap.serviceAccountName" . }}
  labels:
{{ include "goatsnap.labels" . | nindent 4 }}
{{- end -}}
